odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 50
two_d_mode: true

odom0: encoder_imu_odometry/odometry
odom0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_queue_size: 100

vins0: vins_estimator/odometry
vins0_config: [true, true, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false, false, false]
vins0_differential: false
vins0_queue_size: 20
vins0_remove_gravitational_acceleration: true
